version: "3"
services:
  db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - ./docker/db/initdb:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF8"
    restart: always
    user: root

volumes:
  pgdata:
